development:
  adapter: mysql
  database: con_db
  username: root
  password: qwe123
  host: 127.0.0.1
  port: 3306
test:
  adapter: mysql
  database: con_db
  username: root
  password: qwe123
  host: 127.0.0.1
  port: 3306
production:
  adapter: mysql
  database: con_db
  username: root
  password: qwe123
  host: 127.0.0.1
  port: 3306
